run_id: null
dataset:
  module: data.data_loader
  class: H5ADLoader
  path: mnt/DATA/luad_brca/luad/luad_analysis1.h5ad
  load_raw: true
  label_key: group_id
  batch_key: sample_id
  layer_name: X
  train_test_split: data_splits/luad/luad1/train_test_split.json
  cv_splits: data_splits/luad/luad1/cv_splits.json
  dataset_name: luad1
  task_name: cancer_stage_classification
qc:
  min_genes: 10
  min_cells: 10
preprocessing:
  skip: true
  normalize: true
  target_sum: 10000
  apply_log1p: true
hvg:
  skip: true
  batch_key: batch
  n_top_genes: 4096
  flavor: seurat
embedding:
  method: scConcept
  module: features.scconcept_extractor
  class: scConceptExtractor
  viz: true
  eval: true
  params:
    model_name: Corpus-30M
    cache_dir: /lotterlab/datasets/VCC/MODEL_CHECKPOINTS/SC_FM_repo_checkpoints/scConcept
    batch_size: 32
    gene_id_column: gene_ids
    repo_id: theislab/scConcept
evaluations:
- type: classification
  skip: false
  params:
    module: models.classify
    class: ClassifierPipeline
    model: random_forest
    n_estimators: 100
    max_depth: 5
    train_funcs:
    - avg
    - mil
    - vote
    cv: true
    cls_level: patient
    label_map:
      early_stage: 0
      late_stage: 1
    viz: true
    eval: true
