run_id: null
dataset:
  module: data.data_loader
  class: H5ADLoader
  path: DATASETS/SCFM_datasets/EvalDatasets/cell_identity_batch/mouse_pancreas_atlas.h5ad
  load_raw: false
  label_key: cell_type
  batch_key: donor_id
  layer_name: X
  train_test_split: null
  cv_splits: null
  dataset_name: mouse_pancreas_atlas
  task_name: label_transfer
qc:
  min_genes: 10
  min_cells: 10
preprocessing:
  skip: false
  normalize: true
  target_sum: 10000
  apply_log1p: true
hvg:
  skip: false
  batch_key: donor_id
  n_top_genes: 4096
  flavor: seurat
embedding:
  method: scConcept
  module: features.scconcept_extractor
  class: scConceptExtractor
  viz: true
  eval: true
  params:
    model_name: Corpus-30M
    cache_dir: /lotterlab/datasets/VCC/MODEL_CHECKPOINTS/SC_FM_repo_checkpoints/scConcept
    batch_size: 32
    gene_id_column: gene_ids
    repo_id: theislab/scConcept
evaluations:
- type: annotation
  skip: false
  params:
    label_key: cell_type
    k: 15
    metric: cosine
    method: sklearn_knn
    split_strategies:
    - even
    - random
    - difficult
    n_random_splits: 10
    random_state: 42
    min_cells_per_type: 2
