run_id: null
dataset:
  dataset_name: gtex_v9
  task_name: batch_bio_integration
  module: data.data_loader
  class: H5ADLoader
  path: DATASETS/SCFM_datasets/EvalDatasets/cell_identity_batch/gtex_v9.h5ad
  load_raw: false
  label_key: cell_type
  batch_key: prep
  layer_name: X
  train_test_split: null
  cv_splits: null
qc:
  min_genes: 10
  min_cells: 10
preprocessing:
  skip: false
  normalize: true
  target_sum: 10000
  apply_log1p: true
hvg:
  skip: false
  batch_key: prep
  n_top_genes: 4096
  flavor: seurat
embedding:
  method: scConcept
  module: extractors.scconcept_extractor
  class: scConceptExtractor
  viz: true
  eval: true
  params:
    model_name: Corpus-30M
    cache_dir: /lotterlab/datasets/VCC/MODEL_CHECKPOINTS/SC_FM_repo_checkpoints/scConcept
    batch_size: 32
    gene_id_column: gene_id
    repo_id: theislab/scConcept
evaluations:
- type: batch_effects
  skip: false
  params:
    batch_key: prep
    label_key: cell_type
    metric: cosine
    auto_subsample: true
    n_neighbors: 90
    run_baselines: true
    baseline_methods:
    - embed_cell_types
    - embed_cell_types_jittered
- type: biological_signal
  skip: false
  params:
    label_key: cell_type
    metric: cosine
    auto_subsample: true
    leiden_resolution: 0.3
    n_neighbors: 15
- type: annotation
  skip: false
  params:
    label_key: cell_type
    k: 15
    metric: cosine
    method: sklearn_knn
    split_strategies:
    - round_robin
    min_cells_per_type: 2
