run_id: null
dataset:
  dataset_name: bassez_pre
  task_name: batch_bio_integration
  module: data.data_loader
  class: H5ADLoader
  path: DATASETS/SCFM_datasets/Bassez_2021_processed/bassez_combined_preprocessed_prepared.h5ad
  load_raw: false
  label_key: cell_types
  batch_key: donor_id
  filter:
  - column: timepoint
    values:
    - Pre
  layer_name: X
  train_test_split: data_splits/brca_full/brca_cell_type/train_test_split.json
  cv_splits: data_splits/brca_full/brca_cell_type/cv_splits.json
qc:
  min_genes: 10
  min_cells: 10
preprocessing:
  skip: false
  normalize: true
  target_sum: 10000
  apply_log1p: true
hvg:
  skip: false
  batch_key: donor_id
  n_top_genes: 4096
  flavor: seurat
embedding:
  method: scConcept
  module: extractors.scconcept_extractor
  class: scConceptExtractor
  viz: true
  eval: true
  params:
    model_name: Corpus-30M
    cache_dir: ${VCC_CHECKPOINTS_BASE}/scConcept
    batch_size: 32
    gene_id_column: gene_id
    repo_id: theislab/scConcept
evaluations:
- type: batch_effects
  skip: false
  params:
    batch_key: donor_id
    label_key: cell_types
    metric: cosine
    auto_subsample: true
    n_neighbors: 90
    run_baselines: true
    baseline_methods:
    - embed_cell_types
    - embed_cell_types_jittered
- type: biological_signal
  skip: false
  params:
    label_key: cell_types
    metric: cosine
    auto_subsample: true
    leiden_resolution: 0.3
    n_neighbors: 15
- type: annotation
  skip: false
  params:
    label_key: cell_types
    k: 15
    metric: cosine
    method: sklearn_knn
    split_strategies:
    - round_robin
    min_cells_per_type: 2
