run_id: null
dataset:
  module: data.data_loader
  class: H5ADLoader
  path: DATASETS/SCFM_datasets/Bassez_2021_processed/bassez_combined_preprocessed_prepared.h5ad
  load_raw: false
  label_key: cohort
  batch_key: donor_id
  filter:
  - column: timepoint
    values:
    - Pre
  - column: cell_types
    values:
    - Cancer_cell
  layer_name: X
  train_test_split: data_splits/brca_full/brca_chemo/train_test_split_oversampled.json
  cv_splits: data_splits/brca_full/brca_chemo/cv_splits_oversampled.json
  dataset_name: brca_full
  task_name: chemo_sensitivity
qc:
  skip: true
  min_genes: 10
  min_cells: 10
preprocessing:
  normalize: true
  target_sum: 10000
  apply_log1p: true
embedding:
  method: scConcept
  module: features.scconcept_extractor
  class: scConceptExtractor
  viz: true
  eval: true
  params:
    model_name: Corpus-30M
    cache_dir: /lotterlab/datasets/VCC/MODEL_CHECKPOINTS/SC_FM_repo_checkpoints/scConcept
    batch_size: 32
    gene_id_column: gene_ids
    repo_id: theislab/scConcept
evaluations:
- type: classification
  skip: false
  params:
    module: models.classify
    class: ClassifierPipeline
    model: random_forest
    n_estimators: 100
    max_depth: 5
    train_funcs:
    - avg
    - mil
    - vote
    cv: true
    cls_level: patient
    label_map:
      treatment_naive: 0
      neoadjuvant_chemo: 1
    viz: true
    eval: true
